--1
SELECT MODEL
FROM AIRCRAFTS_DATA ad
WHERE AIRCRAFT_CODE IN ('320', '321', '733')

--2
SELECT MODEL
FROM AIRCRAFTS_DATA ad
WHERE AIRCRAFT_CODE NOT LIKE '3%'

--3
SELECT *
FROM TICKETS t
WHERE PASSENGER_NAME LIKE '%OLGA%'
	AND (EMAIL LIKE '%olga%'
		OR EMAIL IS NULL)

--4
SELECT *
FROM AIRCRAFTS_DATA ad
WHERE "RANGE" IN ('5600', '5700')
ORDER BY "RANGE" DESC

--5
SELECT CITY, AIRPORT_NAME
FROM AIRPORTS_DATA ad
WHERE CITY = 'Moscow'
ORDER BY AIRPORT_NAME

--6
SELECT DISTINCT CITY
FROM AIRPORTS_DATA ad
WHERE TIMEZONE LIKE '%Europe%'

--7
SELECT BOOK_REF, TOTAL_AMOUNT * 0.9 AS SUM
FROM BOOKINGS b
WHERE BOOK_REF LIKE '3A4%'

--8
SELECT 'INFORMATION:', 'SEAT #', SEAT_NO, FARE_CONDITIONS
FROM SEATS s
WHERE AIRCRAFT_CODE = '320'
	AND FARE_CONDITIONS = 'Business'

--9
SELECT MIN(TOTAL_AMOUNT), MAX(TOTAL_AMOUNT)
FROM BOOKINGS b
WHERE TRUNC(BOOK_DATE, 'yy') = TO_DATE('01-01-2017')

--10
SELECT MODEL, COUNT(SEAT_NO) AS AMOUNT
FROM AIRCRAFTS_DATA ad
JOIN SEATS s ON s.AIRCRAFT_CODE = ad.AIRCRAFT_CODE
GROUP BY MODEL
ORDER BY AMOUNT DESC

--11
SELECT MODEL, FARE_CONDITIONS, COUNT(SEAT_NO) AS AMOUNT
FROM AIRCRAFTS_DATA ad
JOIN SEATS s ON s.AIRCRAFT_CODE = ad.AIRCRAFT_CODE
GROUP BY MODEL, FARE_CONDITIONS
ORDER BY MODEL, AMOUNT DESC

--12
SELECT PASSENGER_NAME, PHONE, COUNT(TICKET_NO)
FROM TICKETS t
WHERE PASSENGER_NAME LIKE '%ALEKSANDR STEPANOV%'
	AND PHONE LIKE '%11'
GROUP BY PASSENGER_NAME, PHONE

--13
SELECT PASSENGER_NAME, COUNT(TICKET_NO) AS AMOUNT
FROM TICKETS t
WHERE PASSENGER_NAME LIKE '%ALEKSANDR %'
GROUP BY PASSENGER_NAME
HAVING COUNT(TICKET_NO) > 2000
ORDER BY AMOUNT DESC

--14
SELECT TRUNC(DATE_DEPARTURE, 'dd') DAY, COUNT(FLIGHT_ID)
FROM FLIGHTS f
WHERE TRUNC(DATE_DEPARTURE, 'mm') = TO_DATE('01-09-2017')
GROUP BY TRUNC(DATE_DEPARTURE, 'dd')
HAVING COUNT(FLIGHT_ID) > 200
ORDER BY DAY

--15
SELECT CITY
FROM AIRPORTS_DATA ad
GROUP BY CITY
HAVING COUNT(AIRPORT_CODE) > 1
ORDER BY CITY

--16
SELECT MODEL, LISTAGG(SEAT_NO, '; ') WITHIN GROUP (ORDER BY SEAT_NO) AS SEATS
FROM AIRCRAFTS_DATA ad
JOIN SEATS s ON s.AIRCRAFT_CODE  = ad.AIRCRAFT_CODE
GROUP BY MODEL

--17
SELECT CITY, AIRPORT_NAME, DATE_DEPARTURE, FLIGHT_NO
FROM FLIGHTS f
JOIN AIRPORTS_DATA ad ON f.DEPARTURE_AIRPORT = ad.AIRPORT_CODE
WHERE CITY = 'Moscow'
	AND TRUNC(DATE_DEPARTURE, 'mm') = TO_DATE('01-09-2017')

--18
SELECT AIRPORT_NAME, COUNT(FLIGHT_NO) AS AMOUNT
FROM FLIGHTS f
JOIN AIRPORTS_DATA ad ON f.DEPARTURE_AIRPORT = ad.AIRPORT_CODE
WHERE CITY = 'Moscow'
	AND TRUNC(DATE_DEPARTURE, 'yy') = TO_DATE('01-01-2017')
GROUP BY AIRPORT_NAME
ORDER BY AMOUNT DESC

--19
SELECT AIRPORT_NAME, TRUNC(DATE_DEPARTURE, 'mm'), COUNT(FLIGHT_NO) AS AMOUNT
FROM FLIGHTS f
JOIN AIRPORTS_DATA ad ON f.DEPARTURE_AIRPORT = ad.AIRPORT_CODE
WHERE CITY = 'Moscow'
	AND TRUNC(DATE_DEPARTURE, 'yy') = TO_DATE('01-01-2017')
GROUP BY AIRPORT_NAME, TRUNC(DATE_DEPARTURE, 'mm')
ORDER BY TRUNC(DATE_DEPARTURE, 'mm'), AMOUNT DESC

--20
SELECT TICKET_NO, BOOK_REF
FROM TICKETS t
WHERE BOOK_REF LIKE '3A4B%'

--21
SELECT DISTINCT FLIGHT_ID, BOOK_REF
FROM TICKETS t
JOIN TICKET_FLIGHTS tf ON t.TICKET_NO = tf.TICKET_NO
WHERE BOOK_REF LIKE '3A4B%'
ORDER BY FLIGHT_ID DESC